#!/usr/bin/env bash
# Fill winget SHA + Homebrew formula from a published GitHub release.
# Usage:
#   ./scripts/fill-release-packaging.sh            # default: latest tag v0.1.x
#   ./scripts/fill-release-packaging.sh v0.1.8
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
TAG="${1:-}"
if [[ -z "$TAG" ]]; then
  TAG="$(gh release view --json tagName -q .tagName 2>/dev/null || true)"
fi
if [[ -z "$TAG" ]]; then
  TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo v0.1.8)"
fi
VER="${TAG#v}"
echo "fill-release-packaging: tag=$TAG version=$VER"

need() { command -v "$1" >/dev/null 2>&1 || { echo "error: need $1" >&2; exit 1; }; }
need gh
need curl
need python3

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Windows zip SHA (first field of .sha256 asset)
WIN_SHA_FILE="$TMP/win.sha256"
if ! curl -fsSL -o "$WIN_SHA_FILE" \
  "https://github.com/loreste/mako/releases/download/${TAG}/mako-x86_64-pc-windows-msvc.sha256"; then
  echo "error: could not download windows .sha256 for $TAG" >&2
  exit 1
fi
WIN_SHA="$(awk 'NR==1 { print toupper($1) }' "$WIN_SHA_FILE")"
echo "  windows zip sha256: $WIN_SHA"

# Source archive SHA for Homebrew
SRC="$TMP/src.tar.gz"
curl -fsSL -o "$SRC" "https://github.com/loreste/mako/archive/refs/tags/${TAG}.tar.gz"
SRC_SHA="$(shasum -a 256 "$SRC" | awk '{ print $1 }')"
echo "  source tar.gz sha256: $SRC_SHA"

# Multi-file winget manifests (singleton is rejected by microsoft/winget-pkgs).
# Submit under: manifests/l/loreste/mako/<ver>/
WINGET_DIR="$ROOT/packaging/winget"
python3 - "$WINGET_DIR" "$VER" "$TAG" "$WIN_SHA" <<'PY'
import pathlib, re, sys
wdir, ver, tag, sha = sys.argv[1:5]
wdir = pathlib.Path(wdir)
for name in (
    "loreste.mako.yaml",
    "loreste.mako.installer.yaml",
    "loreste.mako.locale.en-US.yaml",
):
    path = wdir / name
    if not path.is_file():
        print(f"  skip missing {path}")
        continue
    text = path.read_text()
    text = re.sub(r"(?m)^PackageVersion:.*$", f"PackageVersion: {ver}", text)
    text = re.sub(
        r"(?m)^(  )?InstallerUrl:.*$",
        f"  InstallerUrl: https://github.com/loreste/mako/releases/download/{tag}/mako-x86_64-pc-windows-msvc.zip",
        text,
    )
    text = re.sub(r"(?m)^(  )?InstallerSha256:.*$", f"  InstallerSha256: {sha}", text)
    text = re.sub(
        r"(?m)^ReleaseNotesUrl:.*$",
        f"ReleaseNotesUrl: https://github.com/loreste/mako/releases/tag/{tag}",
        text,
    )
    text = re.sub(
        r"(?m)^LicenseUrl:.*$",
        f"LicenseUrl: https://github.com/loreste/mako/blob/{tag}/LICENSE",
        text,
    )
    path.write_text(text)
    print(f"  wrote {path}")
# Remove deprecated singleton if present
old = wdir / "mako.locale.en-US.yaml"
if old.is_file():
    old.unlink()
    print(f"  removed deprecated singleton {old}")
PY

FORMULA="$ROOT/Formula/mako.rb"
python3 - "$FORMULA" "$VER" "$TAG" "$SRC_SHA" <<'PY'
import pathlib, sys, re
path, ver, tag, sha = sys.argv[1:5]
text = pathlib.Path(path).read_text()
# Ensure stable url/sha256 lines exist after homepage
if re.search(r'^\s*url\s+"https://github.com/loreste/mako/archive', text, re.M):
    text = re.sub(
        r'^\s*url\s+"https://github.com/loreste/mako/archive[^"]+"',
        f'  url "https://github.com/loreste/mako/archive/refs/tags/{tag}.tar.gz"',
        text,
        count=1,
        flags=re.M,
    )
else:
    text = re.sub(
        r'(homepage\s+"[^"]+"\n)',
        rf'\1  url "https://github.com/loreste/mako/archive/refs/tags/{tag}.tar.gz"\n',
        text,
        count=1,
    )
if re.search(r'^\s*sha256\s+"', text, re.M):
    text = re.sub(r'^\s*sha256\s+"[0-9a-fA-F]+"', f'  sha256 "{sha}"', text, count=1, flags=re.M)
else:
    text = re.sub(
        r'(url\s+"[^"]+"\n)',
        rf'\1  sha256 "{sha}"\n',
        text,
        count=1,
    )
# version assert in test if present
text = re.sub(r'mako0\.\d+\.\d+', f'mako{ver}', text)
pathlib.Path(path).write_text(text)
print(f"  wrote {path}")
PY

# Checksums summary for docs
SUM="$ROOT/packaging/RELEASE-CHECKSUMS-${VER}.md"
{
  echo "# Release checksums ${TAG}"
  echo
  echo "Generated by \`scripts/fill-release-packaging.sh\`."
  echo
  echo "| Asset | SHA-256 |"
  echo "|-------|---------|"
  for a in \
    mako-aarch64-apple-darwin.tar.gz \
    mako-x86_64-unknown-linux-gnu.tar.gz \
    mako-x86_64-pc-windows-msvc.zip
  do
    f="$TMP/${a}.sha256"
    if curl -fsSL -o "$f" "https://github.com/loreste/mako/releases/download/${TAG}/${a}.sha256" 2>/dev/null; then
      h="$(awk 'NR==1{print $1}' "$f")"
      echo "| \`${a}\` | \`${h}\` |"
    fi
  done
  echo "| source \`v${VER}.tar.gz\` | \`${SRC_SHA}\` |"
  echo
  echo "Winget InstallerSha256 (Windows zip, uppercase): \`${WIN_SHA}\`"
} > "$SUM"
echo "  wrote $SUM"

echo "fill-release-packaging: ok"
echo "  next: open winget-pkgs PR; brew audit --strict Formula/mako.rb"
