#!/usr/bin/env bash

# Archivo de salida
OUTPUT_FILE="docs/PROJECT_STRUCTURE.md"

# Asegurar que exista el directorio docs/
mkdir -p docs

echo "# Mako Repository Structure" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "This file is automatically generated by \`make structure\` (\`./scripts/update_structure.sh\`). Do not edit directly." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo '```text' >> "$OUTPUT_FILE"

# Genera el árbol ignorando binarios, cachés y carpetas de compilación
if command -v tree &> /dev/null; then
    tree -I 'target|.git|.mko|out|*.dSYM|node_modules' --noreport >> "$OUTPUT_FILE"
else
    # Si no tiene 'tree', usa git ls-files
    git ls-files >> "$OUTPUT_FILE"
fi

echo '```' >> "$OUTPUT_FILE"

echo "✅ Estructura generada correctamente en $OUTPUT_FILE"